// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.
// Subscribe to see which companies asked this question

// Hide Tags Hash Table Bit Manipulation
// Hide Similar Problems (E) Single Number

public class Solution {
    public char findTheDifference(String s, String t) {

        int[] diff = new int[26];
        for (int i = 0; i < t.length(); i++) {
            int index = t.charAt(i) - 'a';
            diff[index]++;
        }
        
        for (int i = 0; i < s.length(); i++) {
            int index = s.charAt(i) - 'a';
            diff[index]--;
        }
        
        for (int i = 0; i < diff.length; i++) {
            if (diff[i] != 0) {
                return (char)('a'- 0 + i);
            }
        }
        
        return 'a';
    }
}